### ISSUE TITLE
connectable = context.config.attributes.get("connection", None) returns an `Engine` object when `sqlalchemy.engine.Connection` is expected

### ISSUE THREAD

**Issue by mukuliskul** [schireson/pytest-alembic#113]
## Problem:
I am currently setting up sanity checks for alembic migrations in my fast-api application using `pytest-alembic`

I have setup my `env.py` to be similar to what is describe in [documentation](https://pytest-alembic.readthedocs.io/en/latest/asyncio.html) for supporting both async and sync requests. The sanity checks `test_model_definitions_match_ddl` and `test_upgrade` seem to failing and they give the error:

`alembic.util.exc.CommandError: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got Engine(sqlite:///)`

## Fix:
We simply need to run `do_run_migrations(connection)` inside our if condition like the following

```python3
if isinstance(connectable, AsyncEngine):
    asyncio.run(run_async_migrations(connectable))
else:
    with connectable.connect() as connection:
        do_run_migrations(connection)
```   

this way we are passing the expected `Connection` object instead of the `Engine` object.

It'll be sweet if you guys could approve this and I can perhaps make a documentation related PR.

**Comment by mukuliskul** [comment]
Update:

I cloned your repo and realized this change already [exists](https://github.com/schireson/pytest-alembic/blob/main/docs/source/asyncio.rst#:~:text=))%0A%20%20%20%20else%3A-,with%20connectable.connect()%20as%20connection%3A,-do_run_migrations(connection), but it not visible on your documentation [here](https://pytest-alembic.readthedocs.io/en/latest/asyncio.html#:~:text=do_run_migrations(connectable)).

**Comment by DanCardin** [comment]
Alas! our docs builds were broken, should be fixed now. Thanks for the report!
