### ISSUE TITLE
alembic_engine fixture should use `sqlalchemy.url` form alembic_config

### ISSUE THREAD

**Issue by mukuliskul** [schireson/pytest-alembic#114]
# Problem

I am currently setting up sanity checks for alembic migrations in my fast-api application using `pytest-alembic`. During this setup I wanted to use my own custom connection string as compared to the default `sqlite:///`.

Whilst reading the [documentation](https://pytest-alembic.readthedocs.io/en/latest/api.html#alembic-config), my first impression was to pass my custom `sqlaclhemy.url` to the fixture called `alembic_config`.

However, after certain errors and attempts I realized I needed to overwrite `alembic_engine` and send my connection string directly instead.

# Fix

I was hoping if it would be easier to simply pass the `sqlalchemy.url` from `alembic_config` to `alembic_engine`. 

It'll be nice if you guys could consider this and I'll be more than happy to make the appropriate changes in a subsequent PR.

**Comment by DanCardin** [comment]
I believe it's more dependent on your particular env.py setup. The default env.py suggested [in the docs](https://pytest-alembic.readthedocs.io/en/latest/setup.html#env-py) does an `if connection is None:`, but that's probably not what you want, if you're manually configuring your own url.

In your case, i'd expect you to just unconditionally read from the config, while directly configuring the sqlalchemy.url through the `alembic_config`.

In any case, it's hard to debug without seeing more of your setup, but sqlalchemy.url config **should** work.
