### ISSUE TITLE
Dataclasses only required for Python < 3.7

### ISSUE THREAD

**Issue by snorfalorpagus** [schireson/pytest-alembic#15]
`dataclasses` is configured as a dependency for Python <= 3.7, but this should be < 3.7 as it is part of the standard library since 3.7.

https://github.com/schireson/pytest-alembic/blob/d9bcfcc709421734e14f3d034bfa77f74c15729e/pyproject.toml#L26

**Comment by DanCardin** [comment]
good catch!

**Comment by DanCardin** [comment]
Fixed by https://github.com/schireson/pytest-alembic/pull/16, released as 0.2.4
