### ISSUE TITLE
False - positives on Models match DDL test

### ISSUE THREAD

**Issue by kpitzen** [schireson/pytest-alembic#20]
Expected behavior:
- When `alembic revision --autogenerate` generates no changes in schema, pytest-alembic should pass on this test

Actual behavior:
- alembic generates no revisions and pytest-alembic fails this test.

![image](https://user-images.githubusercontent.com/4128006/109356808-3ca30c00-784f-11eb-9683-f40083a6de3e.png)

```
Errors:
E   pytest_alembic.plugin.error.AlembicTestFailure: The models decribing the DDL of your database are out of sync with the set of steps described in the revision history. This usually means that someone has made manual changes to the database's DDL, or some model has been changed without also generating a migration to describe that change.
```

**Comment by DanCardin** [comment]
If you're on latest (or close to latest, i'd have to go check the version this was introduced), the test failure ought to output the migration that the pytest-alembic **claims** autogenerate should output, which is where I would start. I suspect some configuration mismatch.

**Comment by kpitzen** [comment]
Closing due to this being a limitation of Redshift, not pytest-alembic.
