### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'get'

### ISSUE THREAD

**Issue by tschm** [schireson/pytest-alembic#29]
Ok, 
awesome tool. I struggle to make it work for projects with multiple schemata. Here are my schemata:

```
from sqlalchemy import Column, String, Integer, MetaData
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base(metadata=MetaData(schema="schemaA"))

# pylint: disable=too-few-public-methods
class User(Base):
    """
    Simple User Table
    """
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    name = Column(String)
```
and
```
from sqlalchemy import Column, String, Integer, MetaData
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base(metadata=MetaData(schema="schemaB"))

# pylint: disable=too-few-public-methods
class User(Base):
    """
    Simple User Table
    """
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    name = Column(String)
```
I then implemented in conftest.py

```
import os
import sqlalchemy
from alembic.config import Config


def resource(name):
    return os.path.join(os.path.dirname(__file__), "resources", name)


def alembic_engine_test(schema):
    engine = sqlalchemy.create_engine("sqlite:///")
    engine.execute(f"ATTACH DATABASE ':memory:' AS {schema}")
    return engine


def alembic_config_test(schema):
    alembic_cfg = Config()
    # correct absolute path of env.py, versions and script.py.mako
    assert os.path.exists(resource(schema))
    alembic_cfg.set_main_option("script_location", resource(schema)) 
    return alembic_cfg
```
And in my test file:

```
import pytest
import pytest_alembic
from common.schemata.schemaA import Base
from tests.conftest import alembic_engine_test, alembic_config_test


@pytest.fixture
def alembic_config():
    """Override this fixture to configure the exact alembic context setup required."""
    return alembic_config_test(Base.metadata.schema)


@pytest.fixture
def alembic_engine():
    """Override this fixture to provide pytest-alembic powered tests with a database handle."""
    return alembic_engine_test(Base.metadata.schema)


@pytest.fixture
def alembic_runner(alembic_config, alembic_engine):
    """Produce an alembic migration context in which to execute alembic tests."""
    with pytest_alembic.runner(config=alembic_config, engine=alembic_engine) as runner:
        yield runner

from pytest_alembic.tests import test_single_head_revision
from pytest_alembic.tests import test_upgrade
from pytest_alembic.tests import test_model_definitions_match_ddl
from pytest_alembic.tests import test_up_down_consistency
```
When I then run the tests with pytest I get

```
cls = <class 'pytest_alembic.executor.CommandExecutor'>
config = <alembic.config.Config object at 0x7f1986611af0>
    @classmethod
    def from_config(cls, config):
>       file = config.get("file", "alembic.ini")
E       AttributeError: 'Config' object has no attribute 'get'
.venv/lib/python3.9/site-packages/pytest_alembic/executor.py:22: AttributeError
```

I am using Alembic 1.6.5.  I guess there is something wrong with my code or less likely something in Alembic is broken. However, there might be an easier approach to use pytest-alembic on projects with multiple Base objects.
Your help is very appreciated...

**Comment by DanCardin** [comment]
so the `alembic_config` fixture is actually not alembic's `Config` object, but rather a config object which **we** use to configure alembic. But even writing that, i realize that's confusing. Not something i'd thought of, to supply a literal alembic config.

You should be able to `return {'script_location': resource(schema)}`, rather than the alembic `Config` object.

**Comment by DanCardin** [comment]
I will say that your need to manually override the fixtures in a context-specific location, as well as manually import the test implementations are a bit unfortunate.

I'll probably need to think on that a bit, but off the top of my head, some kind of more imperative specification of the fixtures like
```
base1_runner = pytest_alembic.create_fixture(...config...)  # which implies the auto-registration of tests per-fixture
base2_runner = pytest_alembic.create_fixture(...config...)

def test_example(base1_runner):
    ...
```
might be more appropriate for this kind of setup, i would wager (if possible)

**Comment by tschm** [comment]
> so the `alembic_config` fixture is actually not alembic's `Config` object, but rather a config object which **we** use to configure alembic. But even writing that, i realize that's confusing. Not something i'd thought of, to supply a literal alembic config.
> 
> You should be able to `return {'script_location': resource(schema)}`, rather than the alembic `Config` object.

Yes, I can confirm that  `return {'script_location': resource(schema)}` does the job

**Comment by tschm** [comment]
> I will say that your need to manually override the fixtures in a context-specific location, as well as manually import the test implementations are a bit unfortunate.
> 
> I'll probably need to think on that a bit, but off the top of my head, some kind of more imperative specification of the fixtures like
> 
> ```
> base1_runner = pytest_alembic.create_fixture(...config...)  # which implies the auto-registration of tests per-fixture
> base2_runner = pytest_alembic.create_fixture(...config...)
> 
> def test_example(base1_runner):
>     ...
> ```
> 
> might be more appropriate for this kind of setup, i would wager (if possible)

I would be most interested in a sketch of this functionality. Here is my current conftest for that purpose

Here's a failed attemptt

```
import os
import sqlalchemy
from alembic import context
from pytest_alembic.runner import runner


def alembic_engine_test(base):
    engine = sqlalchemy.create_engine(url=os.environ["DB_CONNECTION_STRING"])
    engine.execute(f'CREATE SCHEMA IF NOT EXISTS {base.metadata.schema}; COMMIT;')
    base.metadata.drop_all(bind=engine)
    return engine


def alembic_config_test(schema):
    return {"script_location": resource(schema)}


def create_fixture(base):
    config = alembic_config_test(base.metadata.schema)
    engine = alembic_engine_test(base)
    run = runner(config=config, engine=engine)
    return run
```

**Comment by DanCardin** [comment]
I would have expected your originating example's general setup to work. Do you have **something** which works for you today?

If not, reimplementing these sort of fixture bits out of `pytest_alembic.plugin.fixtures` in a test sub module could also maybe work.

This all, at least until i have an alternate solution baked in.

**Comment by tschm** [comment]
I got something working but it's still rather bad and I think I am missing something...

**Comment by tschm** [comment]
Ok, I have found a construction I am happy with. First in the package I have a function giving me a list of Base objects:

```
"""
Little helper to loop over all base objects
"""
from common.schemata.schema_a import Base as BaseA
from common.schemata.schema_b import Base as BaseB

Bases = [BaseA, BaseB]
```
I then have in conftest:

```
import os
import sqlalchemy
from alembic import context

def resource(name):
    return os.path.join(os.path.dirname(__file__), "resources", name)


def alembic_engine_test(base):
    engine = sqlalchemy.create_engine(url=os.environ["DB_CONNECTION_STRING"])
    engine.execute(f'CREATE SCHEMA IF NOT EXISTS {base.metadata.schema}; COMMIT;')
    base.metadata.drop_all(bind=engine)
    return engine


def alembic_config_test(base):
    return {"script_location": resource(base.metadata.schema)}
```
It's then enough to have one brief test_all_schemata.py:

```
import pytest
from tests.conftest import alembic_engine_test, alembic_config_test
import pytest_alembic
from common.schemata.bases import Bases

@pytest.mark.parametrize("base", Bases)
def test_runner(base):
    config = alembic_config_test(schema=base.metadata.schema)
    engine = alembic_engine_test(base=base)

    """Produce an alembic migration context in which to execute alembic tests."""
    with pytest_alembic.runner(config=config, engine=engine) as runner:
        from pytest_alembic.tests import test_upgrade
        from pytest_alembic.tests import test_single_head_revision
        test_upgrade(runner)
        test_single_head_revision(runner)
```

**Comment by DanCardin** [comment]
So i've done some prototyping.

Not that you directly ask for this but: https://github.com/schireson/pytest-alembic/pull/30 allows an `alembic.config.Config` as a return value to `alembic_config`. In and of itself, not super useful necessarily.

More directly related is: https://github.com/schireson/pytest-alembic/pull/31

I've pretty much found that there are two real issues preventing my ideal case:
* pytext fixtures are all name-based. There doesn't seem to be a particularly good way to compose fixtures of unknown name into one another. i.e. ideally it'd be possible to avoid using `alembic_config/alembic_engine/alembic_runner` entirely. But necessarily at least the engine really needs to be separate and that creates a logistical problem.

Truly this whole PR ultimately boils down to
```
def create_fixture(raw_config=None):
    @pytest.fixture
    def _fixture(alembic_engine):
        config = Config.from_raw_config(raw_config)
        with pytest_alembic.runner(config=config, engine=alembic_engine) as runner:
            yield runner
    return _
```
which is a very thin wrapper, around `_fixture` which you **could** just define yourself. And which maybe this is just something which should be covered by documentation versus being bundled.

* automatic test insertion in the way it works with `--test-alembic` doesn't really work when this plugin's tests can't assume a specific fixture name. And it doesn't seem possible to insert new tests at fixture creation-time.

So the UX of the "solution" in [my PR](https://github.com/schireson/pytest-alembic/pull/31.
https://github.com/schireson/pytest-alembic/pull/31/files#diff-a580bbabbc948e7cf1eb18b714712ea4847ba5c655db0ee8177c83d07260f13bR1) ends up just redefining the tests locally where it uses the alternate runner, because of the aforementioned issues with pytest.

**Comment by DanCardin** [comment]
Your last comment kind of realizes a lot of what i mention above too. So I can absolutely finish fleshing out `create_fixture` for a modicum of convenience to you, or I can leave it as is, and simply document the way one might manually make use of a custom `runner` fixture to essentially realize the pattern in the example when you have more than one history.

**Comment by tschm** [comment]
Great, looking back I have learnt a lot from your examples initially. I think you could make it an example. From this particular problem users may learn more about pytest-alembic. Note how I avoid fixtures in my test_runner. Having said that I see that my approach is less flexible and less clean than separating the construction of the fixtures and the execution of the tests.

Would you say it is a bad idea to have multiple schemeta (and hence multiple Base objects) within one project?

**Comment by tschm** [comment]
After some gymnastics with pytest I ended up with a cleaner version:

```
import pytest
import sqlalchemy
import pytest_alembic

from tests.conftest import resource
from common.schemata.bases import Bases

def config(base):
    return {"script_location": resource(base.metadata.schema)}

def engine(base):
    engine = sqlalchemy.create_engine('sqlite:///:memory:', echo=False)
    engine.execute(f"ATTACH DATABASE ':memory:' AS {base.metadata.schema}")
    # this table has to be deleted separately as it is not part of the base.metadata
    engine.execute(f'DROP TABLE IF EXISTS {base.metadata.schema}.alembic_version;')
    base.metadata.drop_all(bind=engine)
    return engine

@pytest.fixture(params=Bases)
def runner(request):
    base = request.param
    with pytest_alembic.runner(config=config(base), engine=engine(base)) as runner:
        yield runner

def test_match_dll(runner):
    from pytest_alembic.tests import test_model_definitions_match_ddl
    test_model_definitions_match_ddl(runner)

def test_single_head(runner):
    from pytest_alembic.tests import test_single_head_revision
    test_single_head_revision(runner)

def test_upgrade(runner):
    from pytest_alembic.tests import test_upgrade
    test_upgrade(runner)

def test_up_down(runner):
    from pytest_alembic.tests import test_up_down_consistency
    test_up_down_consistency(runner)
```
I still find it odd that I can not import your test_* earlier. Such attempts trigger their execution. Runner is essentially a group of fixtures. One fixture for each base...

**Comment by DanCardin** [comment]
> Great, looking back I have learnt a lot from your examples initially. 
Nice! Happy side-effect then. The examples are a necessary part of integration testing alembic code, and how pytest's testdir fixture works.

> Would you say it is a bad idea to have multiple schemeta (and hence multiple Base objects) within one project?
I mean, if it's for a single database, i wouldn't. If you can join across it (which is perfectly valid with schemas), i would colocate the history.

But I've totally had multi-db (postgres + redshift, or postgres + other) projects, for which this would be essentially necessary, for sure.

> <code block>
Yea, see this very much approaches the example produced by my 2nd PR, where `runner` here is essentially the return value of `create_fixture`.

> I still find it odd that I can not import your test_* earlier.
If i understand correctly what's happening, this is pytest's test resolution. It will try to execute any test_* function in scope. You could alternatively `from pytest_alembic import tests` or `import pytest_alembic.tests` at the module level, to avoid inlining your imports.
