### ISSUE TITLE
Test failures resulting from env.py not being imported with the app_context()

### ISSUE THREAD

**Issue by samgqroberts** [schireson/pytest-alembic#34]
First off - love the project :)

I believe this is an issue with using `pytest-alembic` out-of-the-box with `Flask-SQLAlchemy` / `Flask-Migrate` project.

I encountered a `test_upgrade` error ending in:

```
E               pytest_alembic.plugin.error.AlembicTestFailure: Failed to upgrade through each revision individually.
```

The relevant parts of the stacktrace above it seem to be:
```
    from __future__ import with_statement
    
    import logging
    from logging.config import fileConfig
    
    from flask import current_app
    
    from alembic import context
    from curation.workspace import INPUT_DATA_TABLE_PREFIX
    
    # this is the Alembic Config object, which provides
    # access to the values within the .ini file in use.
    config = context.config
    
    # Interpret the config file for Python logging.
    # This line sets up loggers basically.
    fileConfig(config.config_file_name)
    logger = logging.getLogger("alembic.env")
    
    # add your model's MetaData object here
    # for 'autogenerate' support
    # from myapp import mymodel
    # target_metadata = mymodel.Base.metadata
    config.set_main_option(
        "sqlalchemy.url",
>       str(current_app.extensions["migrate"].db.get_engine().url).replace("%", "%%"),
    )

migrations/env.py:26:
```

and below that:

```
    def _find_app():
        top = _app_ctx_stack.top
        if top is None:
>           raise RuntimeError(_app_ctx_err_msg)
E           RuntimeError: Working outside of application context.
E           
E           This typically means that you attempted to use functionality that needed
E           to interface with the current application object in some way. To solve
E           this, set up an application context with app.app_context().  See the
E           documentation for more information.

venv/lib/python3.9/site-packages/flask/globals.py:47: RuntimeError
```

It looks like my migrations/env.py file needs to be imported `with` an `app_context()`. Providing this context myself like below got me past the issue:

```
from pytest_alembic import tests

def test_upgrade(app, alembic_runner):
    with app.app_context():
        tests.test_upgrade(alembic_runner)
```

For reference, I'm using Flask-Migrate, and I had to override the alembic_config fixture to successfully find my alembic.ini:

```
@pytest.fixture
def alembic_config():
    return {"file": "migrations/alembic.ini"}
```

I'll also note that on this project using `pytest --test-alembic` always matched all of my tests, and none of the built-in tests (had the same effect as simply `pytest`. I had to import from `pytest_alembic.tests` right from the get-go to get anything running.

Thanks!

**Comment by DanCardin** [comment]
> ```
>     config.set_main_option(
>         "sqlalchemy.url",
> >       str(current_app.extensions["migrate"].db.get_engine().url).replace("%", "%%"),
>     )

For this, I would recommend following the suggestion here: https://pytest-alembic.readthedocs.io/en/latest/setup.html#env-py.

Specifically this makes the default `alembic_runner` fixture used by the default test impls use the engine generated by your tests, rather than the ones your default `env.py` might naturally pick up.

This may or may not solve your problem automatically, since it will not be using that `set_main_option` option, and therefore wont be using `current_app`. Happy (imo) side-effect is you'd not be using the real-world env.py settings and risk actually running these migrations against a live database.

If you're using flask-sqlalchemy or something else which im pretty sure forces you to **still** have a live `app` context in these sort of situations, you could then probably do something like suggested [lower in that page](https://pytest-alembic.readthedocs.io/en/latest/setup.html#fixtures)

```
@pytest.fixture
def alembic_engine(app):
    with app.app_context():
        return ...however you get your engine...
```

> I'll also note that on this project using pytest --test-alembic always matched all of my tests, and none of the built-in tests (had the same effect as simply pytest. I had to import from pytest_alembic.tests right from the get-go to get anything running.

This probably depends on how/where you run your tests normally. The `--test-alembic` flag **only** causes the default tests to be automatically included (by inserting them at [pytest_alembic_tests_folder](https://pytest-alembic.readthedocs.io/en/latest/running.html#config (default `tests/`).

So the default assumption is that your tests live at `tests/`, and you'd run tests like `pytest --test-alembic tests` (or configure your pytest default folders). In your particular case currently, where you're redeclaring your own `test_upgrade`, it wont have any effect (with that being said, my above suggestion would mean you shouldn't need to define your own versions of the tests in the first place.

If you want to specifically run only the alembic tests, you can use the [alembic mark](https://pytest-alembic.readthedocs.io/en/latest/running.html?highlight=marks#pytest-marks). So `pytest -m alembic` if you have your own custom tests, or `pytest --test-alembic -m alembic tests` if you use the default tests (to include them, then select only them).

**Comment by DanCardin** [comment]
Let me know if any of this ends up working out, I can add a specific note about compatibility with flask-migrate

**Comment by DanCardin** [comment]
Assuming everything worked out, at best there's some documentation improvements to extract out of this, but I'm not actually sure what you landed on or what would be the most useful information to include.

So i'm gonna close this issue out for now, but (anyone!) let me know otherwise and I can re-open

**Comment by samgqroberts** [comment]
Hi! Sorry for the long delay in getting back to you.

#### run_migrations_online() update

Per your first suggestion to follow the docs and update `run_migrations_online()`, for reference here's what gets placed in `migrations/env.py` by default by Flask-Migrate's `init` command, which is a bit different than what non-Flask-Migrate Alembic usage seems to put in:
```
def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """

    # this callback is used to prevent an auto-migration from being generated
    # when there are no changes to the schema
    # reference: http://alembic.zzzcomputing.com/en/latest/cookbook.html
    def process_revision_directives(context, revision, directives):
        if getattr(config.cmd_opts, 'autogenerate', False):
            script = directives[0]
            if script.upgrade_ops.is_empty():
                directives[:] = []
                logger.info('No changes in schema detected.')

    connectable = current_app.extensions['migrate'].db.get_engine()

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            process_revision_directives=process_revision_directives,
            **current_app.extensions['migrate'].configure_args
        )

        with context.begin_transaction():
            context.run_migrations()
```

I believe this means that alembic is already set up by Flask-Migrate to get the database engine from the flask app's configuration, which (if run in an `app_context()`) should yield the correct engine in both prod and testing. 

#### alembic_engine fixture

I tried your suggestion for this, and it worked! I added this fixture to conftest:
```
@pytest.fixture
def alembic_engine(app):
    with app.app_context():
        yield db.get_engine()
```
where `db` is the SQLAlchemy object that I run `db.init_app(app)` in my `create_app()` factory. Now, I don't need to wrap my custom pytest test invocations in an app_context(), so, eg., this just works:
```
def test_single_head_revision(alembic_runner):
    tests.test_single_head_revision(alembic_runner)
```

#### test invocation

Your suggestions about the test invocations also worked! I think I just had an incorrect understanding of `--test-alembic`, like I thought it would run those tests exclusively, and since in my previous configuration I had to wrap the test runs in `app_context()` anyway I stopped investigating it. So on top of the `alembic_engine()` fixture I can now remove all of those custom test invocations entirely. 

So it looks like you're right, there's likely no code changes here. At best we could consider a new docs page specifically targeting people using Flask-SQLAlchemy and Flask-Migrate, since I'd imagine that's not an uncommon vector. I know I was confused and a little discouraged looking at the `run_migrations_online()` part in the docs and not seeing it line up with my own `env.py`.
