### ISSUE TITLE
Need a clean way to disable test_up_down_consistency or limit to a specific revision

### ISSUE THREAD

**Issue by unj1m** [schireson/pytest-alembic#41]
Howdy, I inherited some migrations that can't be downgraded. 

Some ideas:

1. Stop running downgrades if one raises `NotImplementedError`.
    This seems like a fairly clean way to tell `test_up_down_consistency` that you can't get there from here. :)

2. Provide a way to specify a revision not to downgrade from and beyond.

3. Provide a way to disable `test_up_down_consistency`. Is there a way and I missed it?

    I found a hacky way that I'm using for now. :)

**Comment by unj1m** [comment]
BTW, thanks for creating this package!!!

**Comment by DanCardin** [comment]
3. individual tests can be disabled in pytest config, [for example](https://github.com/schireson/pytest-alembic/blob/6f52c46ccd93e9da1f9195fb5cb10fff3ea0b64a/examples/test_empty_history/setup.cfg)

2. I've got a pending PR for a more strict downgrade-testing test, and had been noodling around basically this. It's a good idea, i think i'll implement as a per-revision piece of configuration.

1. This isn't a bad idea either, although i dont know that I'd recommend using it, because an individual might naively opt the history out of being tested. I think it might still be worthwhile to use this heuristic to avoid failing the test, but emit a warning, suggesting the use of option 2.

**Comment by unj1m** [comment]
> 3. individual tests can be disabled in pytest config, [for example](https://github.com/schireson/pytest-alembic/blob/6f52c46ccd93e9da1f9195fb5cb10fff3ea0b64a/examples/test_empty_history/setup.cfg)

Cool. That worked. Thanks.

> 4. I've got a pending PR for a more strict downgrade-testing test, and had been noodling around basically this. It's a good idea, i think i'll implement as a per-revision piece of configuration.
> 5. This isn't a bad idea either, although i dont know that I'd recommend using it, because an individual might naively opt the history out of being tested. I think it might still be worthwhile to use this heuristic to avoid failing the test, but emit a warning, suggesting the use of option 2.

+1

**Comment by DanCardin** [comment]
<img width="62" alt="Screen Shot 2021-11-29 at 8 09 20 PM" src="https://user-images.githubusercontent.com/701548/143967291-af821631-84a7-4b9e-b77c-da02644babce.png">
I did **not** say 3, 4, 5 github, thank you very much!

**Comment by DanCardin** [comment]
https://github.com/schireson/pytest-alembic/pull/42 Implements 1/2

**Comment by DanCardin** [comment]
Released in 0.6.0, just now

**Comment by unj1m** [comment]
Here's an update:

- Getting this configured took a bit of time to figure out.  I seem to need to define an alembic configuration, to force use of Postgres rather than sqlite.  This got a little complicated. :)  Here's what I ended up with:

  ```
  @pytest.fixture
  def alembic_config(test_db_url):
      """configure the exact alembic context setup required.
      """
      import alembic.config
      import pytest_alembic.config

      url = f"{test_db_url}-{datetime.datetime.now().isoformat()}"
      create_database(url)
      alembic_config = alembic.config.Config()
      alembic_config.set_main_option("sqlalchemy.url", url)
      alembic_config.set_main_option("script_location", "alembic")
      alembic_config.config_file_name = "alembic.ini"

      config = pytest_alembic.config.Config(
          alembic_config=alembic_config,
          minimum_downgrade_revision="e94cd4fbd98f",
          )

      yield config
      drop_database(url)


  @pytest.fixture
  def alembic_engine(alembic_config):
      """provide pytest-alembic powered tests with a database handle."""
      import sqlalchemy

      return sqlalchemy.create_engine(
          alembic_config.alembic_config.get_main_option("sqlalchemy.url"))
  ```

  Maybe there's a simpler way to have done this.  I learned about `pytest_alembic.config.Config` from the PR. :) 
  I don't recall seeing it the docs.

- in `test_up_down_consistency`, https://github.com/schireson/pytest-alembic/pull/42/files#diff-5211d9dc97ef3fa1e941cf15812bd4a5514945ca15a92cad1e01e10629f18055R138, when re-migrating, index is bigger than it needs to be, at lease in the case where `minimum_downgrade_revision` is set, and the first upgrade is a noop.  Not sure if you care. :)

-  Enabling `test_up_down_consistency` helped me find and fix multiple downgrade bugs.

Thanks again!

**Comment by DanCardin** [comment]
I don't know to what extent you followed https://pytest-alembic.readthedocs.io/en/latest/setup.html or not. That will likely address your needing to set the sqlalchemy.url (although there's no reason I **cant** support it)

So I think it's primarily `config_file_name` that's in your way. Admittedly, this part of the interface is probably under baked depending on what alembic customizations you have set.

```
pytest_alembic.config.Config(
    config_options=dict(
        script_location='alembic',
        sqlalchemy_url=url,
        config_file_name="alembic.ini",
    ),
    minimum_downgrade_revision="e94cd4fbd98f",
)
```
is probably what we want, but `config_file_name` isn't being pulled out (yet)

> in test_up_down_consistency, #42 (files), when re-migrating, index is bigger than it needs to be, at lease in the case where minimum_downgrade_revision is set, and the first upgrade is a noop. Not sure if you care. :)
innnnnteresting. This might have just been an oversight, but i'll take a look thanks!

**Comment by DanCardin** [comment]
Ah actually, what you're setting as `config_file_name` can be sent as the first argument to `Config`, and is available today through the `file` `config_options` key

**Comment by DanCardin** [comment]
https://github.com/schireson/pytest-alembic/pull/43, adds `config_file_name` as an optional alias to `file`; as well as `sqlalchemy.url` (though if you make the adjustments suggested in the linked setup docs, you could avoid that (granted perhaps this is nicer).

Finally, i might suggest pytest-mock-resources.readthedocs.io/, if it's an option, versus manually manipulating your own database creation/cleanup.

**Comment by unj1m** [comment]
> I don't know to what extent you followed https://pytest-alembic.readthedocs.io/en/latest/setup.html or not.

I tried, but I ended up with sqlite. That can work for very simple applications, but wouldn't work there.  I really need PostgreSQL, and our test machinery already manages a test PostgreSQL database server. (And creating test databases within the existing server is pretty fast.)

**Comment by unj1m** [comment]
> Finally, i might suggest https://pytest-mock-resources.readthedocs.io/, if it's an option, versus manually manipulating your own database creation/cleanup.

I'm a big fan of mocking, but I find trying to mock databases for applications with non-trivial database interactions to be a road to hell. :)

In previous projects, I've used sqlite as a stand-in for Big Query and Hive, and that was a win, but required lots of hijinks. :)

**Comment by DanCardin** [comment]
> I tried, but I ended up with sqlite.

the setup suggestions (specifically the env.py change suggestion) wouldn't preclude sqlite. You're already overriding `alembic_engine`, so i would **expect** you to get whatever engine you provide there set into alembic context in the context of your tests.

> I'm a big fan of mocking, but I find trying to mock databases for applications with non-trivial database interactions to be a road to hell. :)

Perhaps that name isn't super intuitive then, it tries to give you literal handles to the thing. So `postgres = pytest_mock_resources.create_postgres_fixture()`, for example. or `postgres = pytest_mock_resources.create_postgres_fixture(ModelBase)` where it auto populates the tables among other options.

In particular it's very useful to us when coupled with pytest-alembic because these tests are very often super slow by comparison to normal tests, and pytest-mock-resources (if it works for your project) can be safely run in parallel on the same postgres instance.
