### ISSUE TITLE
TypeError: table() missing 1 required positional argument: 'connection'

### ISSUE THREAD

**Issue by mv-per** [schireson/pytest-alembic#52]
version: 0.8.0 (most recent version on conda)

When using `alembic_runner.table_at_revision(table_name)`  the  following exception raises:

` 
self.connection_executor.table(revision=revision, name=name, schema=schema)

TypeError: table() missing 1 required positional argument: 'connection'
`

Downgrading to 0.3.1 works fine.

**Comment by DanCardin** [comment]
Oof, sorry about that i see the bug, and this function clearly has no tests 😬. I’ll submit a fix likely tomorrow afternoon or monday morning

**Comment by DanCardin** [comment]
Released in 0.8.2
