### ISSUE TITLE
Cannot create Enum columns when running first migration

### ISSUE THREAD

**Issue by theoturner** [schireson/pytest-alembic#60]
Take a first migration that has an enum column:
```py
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ee70440ea5c7'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table('my_table',
        sa.Column("id", sa.Integer(), nullable=False)
        sa.Column('my_enum', sa.Enum('A', 'B', name='my_enum'), nullable=False),
    )

def downgrade():
    op.drop_table('my_table')
```
With this, we can successfully run `alembic upgrade head`.

However, when we run `pytest --test-alembic`, `test_upgrade` fails:
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateObject) type "my_enum" already exists
```

A common fix for this is to use the `postgresql.ENUM` and set `create_type=False` - but note the column doesn't exist yet, so we do need to create the type!

```py
from sqlalchemy.dialects.postgresql import ENUM

...

def upgrade():
    op.create_table('my_table',
        sa.Column("id", sa.Integer(), nullable=False)
        sa.Column('my_enum', ENUM('A', 'B', name='my_enum', create_type=False), nullable=False),
    )
```

We now predictably end up with the type doesn't exist error:
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedObject) type "my_enum" does not exist
```

We can also create the type separately:
```py
def upgrade():
    my_enum = sa.Enum('A', 'B', name='my_enum')
    my_enum.create(op.get_bind())
    op.create_table('my_table',
        sa.Column("id", sa.Integer(), nullable=False)
        sa.Column('my_enum', my_enum, nullable=False),
    )
```

But again with `pytest --test-alembic`, we get the first error:
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateObject) type "my_enum" already exists
```

How do I create types on first migration with pytest-alembic?

**Comment by theoturner** [comment]
The solution is to use two migrations: one which creates the type (`create_type=True`), and one which creates the tables (`create_type=False`).

First migration:
```py
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = 'ee70440ea5c6'
down_revision = None
branch_labels = None
depends_on = None

MY_ENUM = ENUM('A', 'B', name='my_enum')

def upgrade():
    MY_ENUM.create(op.get_bind())

def downgrade():
    MY_ENUM.drop(op.get_bind())
```
Second migration:
```py
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = 'ee70440ea5c7'
down_revision = 'ee70440ea5c6'
branch_labels = None
depends_on = None

def upgrade():
    op.create_table('my_table',
        sa.Column("id", sa.Integer(), nullable=False)
        sa.Column('my_enum', ENUM('A', 'B', name='my_enum', create_type=False), nullable=False),
    )

def downgrade():
    op.drop_table('my_table')
```

We can now run upgrades/downgrades and `pytest --test-alembic` without issue!

**Comment by DanCardin** [comment]
My assumption is that the tests were (assuming it was up-down-consistency that was failing) correctly encountering that your migrations weren't able to round-trip the migration because your downgrade wasn't undoing what the upgrade did (i.e. secretly create a `type`)

For what it's worth, i think you could have kept one migration if you wanted; and just included the explicit `MY_ENUM.drop(op.get_bind())` in the downgrade.

**Comment by theoturner** [comment]
As above, it's the `test_upgrade` step that was failing. Thought it would be good to add this issue here in case anyone else has the same problem. Thanks for the fast reply!
