### ISSUE TITLE
Running with `--test-alembic` creates tests in the wrong directory?

### ISSUE THREAD

**Issue by jarviliam** [schireson/pytest-alembic#77]
Thank you for the wonderful plugin and framework for running tests for migrations.

I've installed the plugin with the following project structure:
```
app/ (application code)
tests/ (tests)
```
Running `pytest` alone defaults to running tests in the `tests/` folder which is expected. However when I attempt to run it with the `--test-alembic` flag it doesn't utilize the alembic_engine fixture in `tests/conftest.py`. Usually when running pytest the tests all run like `tests/**` but with the above flag the alembic tests runs under `app/__init__.py` which makes sense why it can't use the fixture. Even when using the `pytest_alembic_tests_folder` flag it doesn't move the tests.

As a workaround I can just import the tests in a folder under `tests/` and run pytest with an alembic marker but I was just wondering why it keeps trying to create the alembic tests in the `app/` folder 🤔

**Comment by DanCardin** [comment]
This **sounds** like it's the same or similar issue/solution to https://github.com/schireson/pytest-alembic/issues/69#issuecomment-1439061951.

If you're using 0.10.1 https://github.com/schireson/pytest-alembic/commit/cc6076d0834e6cef633e1cc69c47ee01823d1244#diff-29b7bad6b4eb979afb190882fecbca44d0e5b0445087d639b58ab66b2d802397R29, then it may be that your config name is wrong and should be `pytest_alembic_tests_path`.

fwiw, I would **guess** that `pytest` without any path is actually running tests for both `app/` and `tests/` and you just happen to not have any tests in `app/`. Which is probably a contributing factor to the problem, although it **should** certainly work whether `app/` is included or not.

**Comment by jarviliam** [comment]
Thanks for the response, I think the problem is that 3.10.1 isn't pushed to pypi. I'm running 3.10 locally and it doesn't work but pulling this repo and building as a local package runs fine. I think my issue was fixed with this: https://github.com/schireson/pytest-alembic/pull/73

**Comment by DanCardin** [comment]
How odd! I just pushlished 0.10.1 manually, fwiw

**Comment by jarviliam** [comment]
Confirmed its fixed in 0.10.1. Thank you!
