### ISSUE TITLE
alembic_runner.current does not work with alembic_version in different schema

### ISSUE THREAD

**Issue by omer9564** [schireson/pytest-alembic#82]
I'm using Postgres database, I have a schema that has all my tables inside ( including the alembic_version ) 
When I call alembic_runner.current I see that it failed on 
alembic.runtime.migration.py:532
```
if not self._has_version_table():
    return ()
```
going a little more deep I saw that the self.version_table_schema is None because 
MigrationContext.current does `alembic.migration.MigrationContext.configure(connection)` ( pytest_alembic.runner:75 )
by doing so, opts parameter is empty and therefore `opts.get("version_table_schema", None)` returns None ( alembic.runtime.migration.py:182 )

**Comment by DanCardin** [comment]
This seems to imply your `env.py` has a `context.configure(..., version_table_schema='some_schema')` bit of configuration, which I dont **think** should have an effect on anything, beyond how alembic would run normally.

I'm afraid that I'll likely need a stacktrace and an idea of what your `alembic_engine`/ other fixtures look like. Without this, it's not even clear to me what is failing, or if the failure is inside pytest-alembic or not.

Perhaps also some greater sense of what your env.py looks like, pretty much just any non-default options/code that you might be executing.

**Comment by DanCardin** [comment]
Aha, I didn't see your edited comment. This does help illuminate the problem.

**Comment by DanCardin** [comment]
As far as my understanding of the issue goes, should be fixed as of 0.10.6.

Friendly suggestion 😄: I rely heavily on github notifications to become aware of status updates, I'd very likely have fixed the issue more immediately had I been notified of the additional comment. Instead, I happened to look over the issues, and noticed the additional context in the edit.
