### ISSUE TITLE
Consider removing trailing print in runner.py

### ISSUE THREAD

**Issue by Lawouach** [schireson/pytest-alembic#83]
Hello,

I'm assuming the print here isn't strictly necessary:

https://github.com/schireson/pytest-alembic/blob/d308a19b7d02dd00158d18120ba1e224bcbbd280/src/pytest_alembic/runner.py#L176

Can we remove it as this pollutes test results a bit.

Cheers,

**Comment by DanCardin** [comment]
Thanks for the report, I went a bit overboard and enabled much more strict linting generally, which incidentally fixed this. Release v0.10.5 should have the print removed.
