### ISSUE TITLE
The fixture gets slower on each revision I create

### ISSUE THREAD

**Issue by Lawouach** [schireson/pytest-alembic#85]
Hi there,

For a long time now, I've noticed my tests were getting slow. But it has recently come to a point where I had to investigate.
It comes down to a very slow upgrade from the plugin compared to running alembic on its own.

I have 36 revisions and it takes 15 seconds to upgrade them and 7 seconds to downgrade them with the plugin. But only 5 seconds and 3 seconds respectively when I run alembic itself.

My basic test now takes 30 seconds and most of that time is spent in upgrading/downgrading.

I was wondering if you had notice this as well and if there was anything I could do to improve the issue?

I'm running the upgrade/downgrade dance on each test rather than per-session, I guess I could move to a session fixture and find a way to empty the db per test?

Any feedback will be welcome :)

**Comment by DanCardin** [comment]
As-is, we upgrade through each migration individually (i.e. a series of upgrade +1 equivalents), versus where you're locally going to be doing something like `upgrade head`. This is to ensure we can detect which migration is failing during the upgrade process and that it leaves the database in the pre-failing migration state. I may be amenable to adding a configuration option, if you ultimately decide you'd use it.

I'll admit, I haven't deeply considered this library for running **normal** tests, beyond testing your migrations themselves. I've personally always just had dedicated migrations tests, and also tests that run the DDL using SQLalchemy's native mechanisms.

Not that it can't be done, but I dont know that there's **much** we can do to support the usecase in **this** library. Alembic's process (and the way we interact with it) is always going to be slower than the more direct way.

With that said, I suspect you'll be happier overall by running migrations once per session (if you're set on running migrations in tests generally), if you can get it to work well.

---
If you're open to suggestions https://github.com/schireson/pytest-mock-resources, is what this pytest-alembic uses for producing database fixtures, which we also maintain.

You could do something like (untested):

```python
from pytest_mock_resources import create_postgres_fixture

alembic_engine = create_postgres_fixture(). # power pytest-alembic

@pytest.fixture(scope='session')  # get the migrations database to set state
def migrations(alembic_runner):
    # configure it to create a "migrations" database and point at it, instead
    alembic_runner.upgrade_up_to('head')

base_pg = create_postgres_fixture(scope='session', template_database='migrations')  # Use posgres's database template feature

@pytest.fixture(scope='session')  # boilerplate
def pg(migrations, base_pg):
    return base_pg
```

Having written this down now, I can imagine a couple of enhancements to pytest-mock-resources that would streamline this a little. (i.e `database='migrations'` argument and `uses_fixtures='migrations'`)...

with all that said, this only helps if you're using postgres.

**Comment by Lawouach** [comment]
Hey @DanCardin thanks for the solid feedback.

I went ahead and refactored the fixtures so I run the migration per session only. I simply truncate my data after each tests. So my overall test suite went from 30mn to 5mn without loss of understanding of what was going on.

I think that closes it for me :)

Just to give context, I do run my migrations because that's how I do populate my systems. I didn't my test to take a different route and miss potential issues because sqlalchemy create table would do something different than alembic (they shouldn't but I didn't feel like investigating any obscur bugs).

Thanks for the awesome library again.
