### ISSUE TITLE
Adjustments for Compatibility with SQLAlchemy 2.0 and Explicit Transactions

### ISSUE THREAD

**Issue by hutschen** [schireson/pytest-alembic#87]
Hello,

I'm currently using `pytest_alembic` in my project and in the process of adapting it to the changes introduced by SQLAlchemy 2.0. While doing so, I noticed a warning related to the use of implicit transactions.

The warning occurs when I run a test case that uses `alembic_runner.insert_into`. Such a test case looks like this:

```python
def test_migration(
    alembic_runner: MigrationContext
):
    alembic_runner.migrate_up_before("...")
    alembic_runner.insert_into(
        "my_table",
        {
            "id": 1,
            "name": "test",
        },
    )
    # ...
```

Here is the exact warning I receive:

```
.../lib/python3.10/site-packages/pytest_alembic/executor.py:151: RemovedIn20Warning: The current statement is being autocommitted using implicit autocommit, which will be removed in SQLAlchemy 2.0. Use the .begin() method of Engine or Connection in order to use an explicit transaction for DML and DDL statements. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
    connection.execute(table.insert().values(values))
```

The warning suggests that the current implicit autocommit will be removed in SQLAlchemy 2.0, and instead, the `.begin()` method of Engine or Connection should be used to start an explicit transaction for DML and DDL statements. I'm currently using SQLAlchemy version 1.4.48 and Alembic version 1.11.1.

In relation to my code, I noticed that the warning disappears when I change `self.connection.connect()` to `self.connection.begin()` on line 183 of the file [pytest_alembic/executor.py](https://github.com/schireson/pytest-alembic/blob/main/src/pytest_alembic/executor.py#L183).

Since I receive this warning in a component of `pytest_alembic` and not directly in my own code, it seems that adjustments need to be made to `pytest_alembic` itself to accommodate this change. Would it be possible to make these adjustments in a future release?

Thank you in advance!

**Comment by DanCardin** [comment]
Per version 0.10.7, I've added sqlalchemy 2.0 testing across the package, and also added an explicit test for the insert connect/begin line coverage you pointed out.

Thanks for the report!

**Comment by hutschen** [comment]
@DanCardin Thank you for promptly fixing this issue and creating the release!
