### ISSUE TITLE
How to integrate with `create_all` fixture

### ISSUE THREAD

**Issue by conformist-mw** [schireson/pytest-alembic#89]
Hi!

First of all - thank you very much for the project, it helps a lot in solving problems with migrations.

Unfortunately, I ran into a problem when integrating into a project with existing tests.

I have a fixture that creates all the tables from the models once per session, so as not to migrate everything sequentially and it does not let the migration tests work properly. The fixture is like:

```python
@pytest.fixture(scope="session", autouse=True)
def run_migrations(init_db, engine): 
    Model.metadata.create_all(engine)
```

The error I get says that the table from the first migration already exists (which is reasonable, because all the tables in the database have already been created). To get around this, I tried overriding the `alembic_engine` fixture to use sqlite in memory, but the tests still use the database for all other tests.

Then I tried overriding `pytest_alembic_tests_folder`. I created a separate directory with my conftest.py and imported alembic tests there - same errors (pytest still reads tests/conftest.py and creates all tables)

So the main question is, how would one bypass `create_all` for these tests?

Thanks in advance!

**Comment by conformist-mw** [comment]
Okay, the problem was `env.py` and how the database is created. I rewrote the DB creation fixtures for these tests and now everything is ok.

**Comment by asacristani** [comment]
@conformist-mw can you explain how you resolved it?
I am having the same problem

**Comment by conformist-mw** [comment]
Hey @asacristani, I basically put all these tests in separate file to use another temporary database. 
Something like this:

```python
import os

import database  # internal lib  to handle session
import pytest
from pytest_alembic.tests import (  # noqa: F401
    test_model_definitions_match_ddl,
    test_single_head_revision,
    test_up_down_consistency,
    test_upgrade,
)
from sqlalchemy import URL, create_engine
from sqlalchemy_utils import create_database, drop_database

db_name = f"{os.environ['DB_NAME']}_migrations"


@pytest.fixture(autouse=True)
def _mock_db_name(monkeypatch):
    monkeypatch.setenv("DB_NAME", db_name)


@pytest.fixture(scope="session")
def db_url() -> URL:
    return URL.create(
        drivername="postgresql",
        username=os.environ["DB_USER"],
        password=os.environ["DB_PASSWORD"],
        host=os.environ["DB_HOST"],
        port=int(os.environ["DB_PORT"]),
        database=db_name,
    )


@pytest.fixture(scope="session")
def engine(db_url):
    engine_ = create_engine(db_url)
    yield engine_
    engine_.dispose()


@pytest.fixture(scope="session")
def connection(engine):
    conn = engine.connect()
    database.db_session.configure(
        autocommit=False,
        autoflush=False,
        bind=conn,
    )

    return conn


@pytest.fixture(scope="session")
def init_db(engine):  # noqa: PT004
    create_database(engine.url)
    yield
    drop_database(engine.url)


@pytest.fixture(scope="session", autouse=True)
def run_migrations(init_db, engine):  # noqa: ARG001, PT004
    ...
```

**Comment by DanCardin** [comment]
I wouldn't think it should be as complicated as that. The migrations tests need not depend on the same database as your other tests at all, unless I'm misunderstanding something.

```python
from pytest_mock_resources import create_postgres_fixture

alembic_engine = create_postgres_fixture() # or whatever database you use
```

Your `env.py` needs to then be defined in a way ([according to the docs](https://pytest-alembic.readthedocs.io/en/latest/setup.html#env-py)) that reads the pre-configured connection that pytest-alembic will hand it. I imagine that's why it's that much more complex for you.

I'm guessing your `env.py` is setting up the connection itself using the given by your other fixture, which means it ends up sharing the pre-upgraded database.

**Comment by conformist-mw** [comment]
Yep, my conftest just creates all tables without applying the whole set of migrations, that's why I separated it and run only when I need.
