### ISSUE TITLE
Tests using the same database as pytest_alembic are failing on 0.10.7

### ISSUE THREAD

**Issue by thurse93** [schireson/pytest-alembic#91]
Hi!

we are currently trying to upgrade from version `0.10.6` to `0.10.7` in our project. Unfortunately we are experiencing some problems, since the `pytest_alembic` tests seem to produce side effects between tests which are not getting rolled back in the new version.

An excerpt of our migration test module:

```python
import pytest
from pytest_alembic import MigrationContext, tests
from sqlalchemy import Engine


@pytest.fixture()
def alembic_engine(our_custom_engine_fixture: Engine) -> Engine:
    return our_custom_engine_fixture


@pytest.fixture()
def alembic_config() -> dict:
    return {
        "at_revision_data": {...}
    }


def test_single_head_revision(alembic_runner: MigrationContext) -> None:
    tests.test_single_head_revision(alembic_runner)


def test_upgrade(alembic_runner: MigrationContext) -> None:
    tests.test_upgrade(alembic_runner)


def test_model_definitions_match_ddl(alembic_runner: MigrationContext) -> None:
    tests.test_model_definitions_match_ddl(alembic_runner)


def test_up_down_consistency(alembic_runner: MigrationContext) -> None:
    tests.test_up_down_consistency(alembic_runner)

```

We are using our own database engine throughout the entire test session, the changes are getting rolled back after each test. Before version `0.10.7` pytest_alembic rolled the database back by itself. Now our own tests are failing because there are unexpected tables in the database. We assume thats because of the following change in `0.10.7`, where `connection.connect()` is replaced by `connection.begin()`:

https://github.com/schireson/pytest-alembic/compare/v0.10.6...v0.10.7#diff-0108f216ff6e1670b0a351075109c35eb9af378fc93b0442c06a0dd1232607b5L183-R186

We found a workaround for our use case which simply drops the `alembic_version` table and all our schemas after the migration test module ran:

```python
@pytest.fixture(autouse=True, scope="module")
def _teardown_tables(our_custom_engine_fixture: Engine) -> None:
    yield
    with our_custom_engine_fixture.connect() as connection:
        Base.metadata.drop_all(bind=connection)
        connection.execute(text("DROP TABLE IF EXISTS alembic_version"))
        connection.commit()
```

Question is: Is this the intended behaviour of `pytest_alembic`?
We are aware that our setup with a single database for the entire pytest session is a bit of a special case.

Best regards and thank you for your work providing this nice lib!

**Comment by DanCardin** [comment]
**IF** we can support a commit-less round-trip, i'd like to. But it wouldn't surprise me if either alembic or sqlalchemy force our hand eventually (the change you referenced was in trying to match behavior between async and sync code across sqlalchemy 1.x and 2.x).

In general, i'd recommend against relying on the ability to rollback to solve the inter-test state issue, but obviously if it works for you (and we can support it), you do you!
---

So trying to change that back to `.connect`, we get 1 test failure, which I **think** can be attributed to the actual test being bad, and thus fixable.

I made that change because the code block right above it (in async-land) is doing an explicit commit because...async. But i think actually due to changes to the code over time, that block is actually dead code, and gave a false sense of the correct behavior to emulate.

**Comment by thurse93** [comment]
I don't think that there's a need for no commit from our side. Just the expecation that when all pytest_alembic tests are finished (and successful, on failing tests it's more tolerable to have remains imho) we have a clean database to work on further.

We have mechanisms in place that change the test setup to "one db per test" later in our pipeline. But for local development and fast testing it's nice to initialize the database container just one time.

About the last part with failing test in sqlalchemy 2.0: We use sqlalchemy 2.0 in our project and it seems to work just fine, as long as one just revert the `begin()` back to `connect()` so it does not auto-commit on leaving the context manager.

**Comment by thurse93** [comment]
> The problem is that we can't assume anything about the state of the database from inside this library. Your migrations may be manipulating globals like roles. or there may be some prior database state, given your custom fixture. So the only practical options are to totally avoid commits in pytest-alembic and leave it to alembic, or not support it.

That makes sense of course. I didn't mean that pytest_alembic should be able to clean up the mess that migrations or dependant fixtures might create. Just that if you would force the ordering of the tests for example or providing some teardown mechanisms after each test, so that the last step of the pytest_alembic test context is guaranteed to be a down-migration to base, it would rule out the problems on successful test runs in "standard migration scenarios". However this of course introduces another layer of complexity, is hard to debug and could be seen as an anti-pattern (tests depending on tests).

> Are you doing anything particularly custom in the construction of the Engine? Or any particularly non-standard env.py contents? I suppose I'd have expected just the vanilla alembic upgrade +1s that are all occurring internally to be performing commits themselves.

Not really, engine construction is just a `create_engine("postgresql+psycopg://...", connect_args={"options": "-c timezone=Europe/Berlin"}, pool_pre_ping=True)` and our `env.py` looks like this:

```python
from alembic import context
from our_project.database import engine
from our_project.database.schema import Base
from our_project.settings import settings

config = context.config
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    context.configure(
        url=settings.database.dsn,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = config.attributes.get("connection")

    if connectable is None:
        connectable = engine

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
```

> For whatever it's worth, https://pytest-mock-resources.readthedocs.io/ is what we use to manage the database container(s) for us. Which, for postgres, automatically creates internal databases unique to each test, and should be roughly the same speed as using a single container anyways.

Thanks for providing the link, we use parts of this library, too. I looked up the implementation of our internal testing lib and in actually does the same, i.e. creating a new database for each test instead of recreating the container over and over again. In our test setup the tests take about twice as long compared to rolling back the transaction after each test. But that's honestly a whole other topic^^.

Back to my initial question whether this all is expected behaviour of `pytest_alembic`: After all your explanation I'd argue yes, and it should be sufficient to just add a warning in the documentation along the lines of "hey, maybe dont re-use this database in your subsequent test structure as we cannot guarantee that the database state is the same as before the tests". Makes complete sense and all the mentioned workarounds are a result of our test structure and the nature of how alembic and sqlalchemy work.

**Comment by thurse93** [comment]
I'd love to help you out there, but we work in a somewhat air-gapped environment so it's not trivial for me get involved in projects on github, let alone running tests that require images from public registries... If you can point me to things I should try out it will do, And I'll try to recreate the setup at the weekend.

**Comment by DanCardin** [comment]
If you have any sort of `before_revision_data`, sqlalchemy 2, and a migration which actually [depends upon that data existing](https://github.com/schireson/pytest-alembic/blob/main/examples/test_basic_revision_upgrade_data/migrations/versions/bbbbbbbbbbbb_update_foo.py), my failing tests imply you shouldn't be able to see it in migrations without `begin`

**Comment by thurse93** [comment]
Yes, i can confirm that. With 0.10.7 and begin(), I get the data from the select statement, changing that to `connect()` returns nothing.

**Comment by DanCardin** [comment]
Right, and I would assume that's the case in 0.10.6 as well (although 0.10.6 wouldn't have "supported" sqlalchemy 2.0, officially anyway).

You called out `at_revision_data` in the original report, which is effectively the same thing. The fact that you didn't see issues using it in sqlalchemy 2 when it was using `connect` prior to 0.10.6, makes me suspect the `at_revision_data` isn't being depended upon in your migrations anyways? It was much of the purpose of the change, the changes weren't persisting down the migration chain.

If you don't use `at_revision_data`, then you shouldn't have issues with commits.

**Comment by thurse93** [comment]
Sorry for  the late response, has been a busy week.

Yes, we essentially have only one migration in this project because we squash the migrations from time to time. So there's only one `at_revision_data` which should just ensure that we can insert what we expect to insert.

And yes, removing the revision data also migitates the problem.

Thanks for updating the docs and your extensive help!

**Comment by DanCardin** [comment]
feel free to reopen if you dont think this is closed!
