### ISSUE TITLE
Using "alembic_runner" fixture silences application logs.

### ISSUE THREAD

**Issue by a1d4r** [schireson/pytest-alembic#93]
Hi! For testing the application, I created a fixture which initializes the database using alembic_runner. It looks like that and works just find (kinda slow but it does the job).

```python
@pytest.fixture()
def _init_db(alembic_runner: MigrationContext):
    alembic_runner.migrate_up_to("heads", return_current=False)
    yield
    alembic_runner.migrate_down_to("base", return_current=False)
```

I discovered that after replacing `metadata.create_all` with `alembic_runner.migrate_up_to` in `_init_db` fixture, no application logs are shown in the console in failed tests. I spent half a day trying to solve the issue, and surprisingly the following dirty hack fixes it:
```python
@pytest.fixture()
def _init_db(alembic_runner: MigrationContext):
    alembic_runner.migrate_up_to("heads", return_current=False)
    setup_logging(json_logs=settings.logs.json_format, log_level=settings.logs.level)
    yield
    alembic_runner.migrate_down_to("base", return_current=False)
```

* `setup_logging` function configures structlog

If I set up logger before running migrations, I get no logs:
```python
@pytest.fixture()
def _init_db(alembic_runner: MigrationContext):
    setup_logging(json_logs=settings.logs.json_format, log_level=settings.logs.level)
    alembic_runner.migrate_up_to("heads", return_current=False)
    yield
    alembic_runner.migrate_down_to("base", return_current=False)
```

Somehow running `alembic_runner.migrate_up_to` breaks the logger and I can't figure out why.

**Comment by DanCardin** [comment]
My guess would be the default `env.py` content alembic gives you includes something like:

```python
from logging.config import fileConfig
fileConfig(context.config.config_file_name)
```

which messes with preexisting loggers by default.

We have a note about it, although for different reasons, in [the docs](https://pytest-alembic.readthedocs.io/en/latest/setup.html#caplog-issues)
