### ISSUE TITLE
Docs update: `compare_type` now defaults to True

### ISSUE THREAD

**Issue by mbforbes** [schireson/pytest-alembic#94]
Minor suggestion for docs update:

The current setup guide suggests enabling `compare_type=True`:
https://pytest-alembic.readthedocs.io/en/latest/setup.html#optional-but-helpful-additions

But as of Alembic 1.12.0, "The default value of `EnvironmentContext.configure.compare_type` has been changed to True."
https://alembic.sqlalchemy.org/en/latest/autogenerate.html#comparing-types

**Comment by DanCardin** [comment]
news to me! thanks for pointing that out
