### ISSUE TITLE
Is it possible to override database url for migrations?

### ISSUE THREAD

**Issue by a1d4r** [schireson/pytest-alembic#97]
I set up multiple fixtures, as shown in documentation:

```python
@pytest.fixture()
def async_engine(database_settings) -> AsyncEngine:
    return create_async_engine(
        database_settings.url,
        echo=database_settings.echo,
        poolclass=NullPool, 
    )


@pytest.fixture()
def alembic_engine(async_engine):
    return async_engine


@pytest.fixture()
def alembic_config(database_settings):
    return Config(config_options={"sqlalchemy.url": database_settings.url})
```

`database_settings` is a fixture which provides actual settings for the database. URL is different from the one defined in `env.py`. However, when I use `alembic_runner` fixture, the migration is applied to the database specified in `env.py` (`postgresql+asyncpg://user:password@localhost:5433/test`), not `database_settings.url` (`postgresql+asyncpg://user:password@localhost:5433/test_1`):

```python
@pytest.fixture()
def _init_db(alembic_runner: MigrationContext, database_settings):
    with DatabaseJanitor(
        user=database_settings.username,
        host=database_settings.host,
        port=database_settings.port,
        dbname=database_settings.name,
        version="16.0",
        password=database_settings.password,
    ):
        logger.debug(f"Database setup for {database_settings.url}")  # prints postgresql+asyncpg://user:password@localhost:5433/test_1
        current = alembic_runner.migrate_up_to("heads", return_current=True)
        logger.debug("Current revision: %s", current)
        yield
        logger.debug(f"Database teardown for {database_settings.url}").
```

**Comment by DanCardin** [comment]
Did you follow https://pytest-alembic.readthedocs.io/en/latest/setup.html#env-py? Slash what is the rough content of your env.py, where the engine/connection are produced?

It sounds like either the database.url alembic config is not making it into the actual migration, or your env.py is perhaps not reading it?

We've always included the connection conditional in our env.py definitions, but I suppose use of the sqlalchemy.url is fine as well, we should probably add a test to verify this works (although i think it **should** already if there's not a bug)

**Comment by a1d4r** [comment]
Thank you, I was inattentive and forgot to include the following lines in `env.py`
```python
    connectable = context.config.attributes.get("connection", None)
    if connectable is None:
```

By the way, newer version of alembic (with SQLAlchemy 2.0) support async engine out of the box, and it generates the env.py which is a little bit different from this: https://pytest-alembic.readthedocs.io/en/latest/asyncio.html. 

Here is mine:
```python
async def run_async_migrations() -> None:
    """In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = context.config.attributes.get("connection", None)

    if connectable is None:
        connectable = async_engine_from_config(
            config.get_section(config.config_ini_section, {}),
            prefix="sqlalchemy.",
            poolclass=pool.NullPool,
        )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""

    asyncio.run(run_async_migrations())
```

Finally, made it working with pytest-xdist, many thanks for your quick response.
